src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
	 * [Assert\Type("string",message="Le format doit être une date")
	 * @Assert\GreaterThan("today",message="La date d'arrivée doit être ultérieure à la date d'aujourd'hui",groups="front")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
	 * [Assert\Type("string",message="Le format doit être une date")
	 * @Assert\GreaterThan(propertyPath="startDate",message="La date de départ doit être ultérieure à la date d'arrivée")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;
	
	/**
	 * Callback appelé à chaque fois qu'on créé une réservation
	 * @ORM\PrePersist
	 * @ORM\PreUpdate
	 * @return Response
	*/

	public function prePersist() {
		
		if(empty($this->createdAt)) {
			
			$this->createdAt = new \DateTime();
			
		}
		
		if(empty($this->amount)) {
			
			// Prix de l'annonce * nombre de jours
			
			$this->amount = $this->ad->getPrice() * $this->getDuration();
			
		}
		
	}
	
	public function isBookabledays() {
		
		// Connaître les dates déjà réservées
		
		$notAvailableDays = $this->ad->getNotAvailableDays();
		
		// Connaître les dates en cours de réservation
		
		$bookingDays = $this->getDays();
		
		// Comparaison
		
		$notAvailableDays = array_map(function($day) {
			
			return $day->format('Y-m-d');
			
		},$notAvailableDays);
		
		$days = array_map(function($day) {
			
			return $day->format('Y-m-d');
			
		},$bookingDays);
		
		// On retourne vrai ou faux
		
		foreach($days as $day) {
			
			if(array_search($day,$notAvailableDays) !== false) return false;
			
		}
		
		return true;
		
	}
	
	public function getDays() {
		
		$resultat = range($this->startDate->getTimestamp(),$this->endDate->getTimestamp(),24*60*60);
		
		$days = array_map(function($dayTimestamp) {
			
			return new \DateTime(date('Y-m-d',$dayTimestamp));
			
		},$resultat);
		
		return $days;
		
	}
	
	// Calcul du nombre de jours du séjour
	
	public function getDuration() {
		
		$difference = $this->endDate->diff($this->startDate);
		
		return $difference->days;
		
	}
	
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"email"},
 * message="Cette adresse mail est déjà utilisée")
 */

class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
	 * @Assert\NotBlank()
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
	 * @Assert\NotBlank()
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
	 * @Assert\Email(message="Veuillez renseigner un mail valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
	 * @Assert\Url()
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;
	/**
	 * Comparaison du champ ci-dessous avec le champ password
	 *
	 * @Assert\EqualTo(propertyPath="password",message="Les mots de passe ne correspondent pas")
	*/
	public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
	 * @Assert\Length(min=10,minMessage="Votre introduction doit comporter au moins 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
	 * @Assert\Length(min=100,minMessage="Votre description doit comporter au moins 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;
	
	public function getFullName() {
                                             		
    	return "{$this->firstname} {$this->lastname}";
                                             		
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }
	
	/**
	 * Création d'une fonction pour permettre d'initialiser le slug (avant la persistance et avant la màj)
	 * 
	 * @ORM\PrePersist
	 * @ORM\PreUpdate
	*/
	
	public function initializeSlug() {
                                                                              		
        if(empty($this->slug)) {
                                                                              			
            $slugify = new Slugify();
                                                    
            $this->slug = $slugify->slugify($this->firstname.' '.$this->lastname);
                                                                              			
        }
                                                                              		                          		
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }
	
	public function getRoles() {
                                             		
        $roles = $this->userRoles->map(function($role) {
                              						
        return $role->getTitle();
        })->toArray();
                              		
        $roles[]='ROLE_USER';
                              		
        return $roles;
                                             		
    }
	
	
	public function getSalt() {}
	
	public function getUsername() {
                                             		
        return $this->email;
                                             		
    }
	
	public function eraseCredentials() {}

    /**
     * @return Collection|Role[]
     */
	
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
	
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Form\DataTransformer\FrToDatetimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{
	
	private $transformer;
	
	public function __construct(FrToDatetimeTransformer $transformer) {
		
		$this->transformer = $transformer;
		
	}
	
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('startDate',TextType::class,$this->getConfiguration("Date d'arrivée","La date de votre arrivée"))
            ->add('endDate',TextType::class,$this->getConfiguration("Date de départ","La date de votre départ"))
			->add('comment',TextareaType::class,$this->getConfiguration(false,"Ajoutez un commentaire sur votre séjour",['required'=>false]))
        ;
		
		$builder->get('startDate')->addModelTransformer($this->transformer);
		$builder->get('endDate')->addModelTransformer($this->transformer);
		
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
			'validation_groups' => ['Default','front']
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

class BookingController extends AbstractController
{
    /**
	 * Permet d'afficher le formulaire de réservation
     * @Route("/ads/{slug}/book", name="booking_create")
	 * @IsGranted("ROLE_USER")
	 * 
	 * @return Response
     */
	
    public function book(Ad $ad,Request $request,EntityManagerInterface $entityManager)
    {
        
		$booking = new Booking();
		$form = $this->createForm(BookingType::class,$booking);
		
		$form->handleRequest($request);
		
		if($form->isSubmitted() && $form->isValid()) {
			
			$user = $this->getUser();
			
			$booking->setBooker($user)
					->setAd($ad);
			
			// Si les dates ne sont pas disponibles
			
			if(!$booking->isBookabledays()) {
				
				$this->addFlash("warning","Ces dates ne sont pas disponibles");
				
			}
			
			else {
			
			$entityManager->persist($booking);
			$entityManager->flush();
			
			return $this->redirectToRoute("booking_show",['id'=>$booking->getId(),'alert'=>true]);
				
			}
			
		}
		
		return $this->render('booking/book.html.twig', [
        	'ad'=>$ad,
			'form'=>$form->createView()
        ]);
    }
	
	/**
	 * Affiche une réservation
	 * @Route("/booking/{id}",name="booking_show")
	 * @param Booking $booking
	 * @return Response
	*/
	
	public function show(Booking $booking,Request $request,EntityManagerInterface $entityManager) {
		
		$comment = new Comment();
		
		$form = $this->createForm(CommentType::class,$comment);
		
		$form->handleRequest($request);
		
		if($form->isSubmitted() && $form->isValid()) {
			
			$comment->setAd($booking->getAd())
					->setAuthor($this->getUser());
			
			$entityManager->persist($comment);
			$entityManager->flush();
			
			$this->addFlash("success","Votre commentaire a bien été enregistré.");
			
		}
		
		return $this->render("booking/show.html.twig",['booking'=>$booking,'form'=>$form->createView()]);	
		
	}
	
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formulaire de réservation{% endblock %}

{% block stylesheets %}
	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">

{% endblock %}

{% block body %}

	<div class="container mt-5">

		<h1 class="h2">Réservation pour l'annonce <br> <small>{{ad.title}}</small></h1>
		
		<h5>Vous allez réserver le bien de <strong><em>{{ad.author.fullName}}</em></strong>. Voir plus de biens de ce <a href="{{path('user_show',{'slug':ad.author.slug})}}">loueur</a>.</h5>
		
		{{form_start(form)}}
		
			<div class="row">
		
				<div class="col mt-4 mb-4">
				
					{{form_row(form.startDate)}}
				
				</div>
				
				<div class="col mt-4 mb-4">
				
					{{form_row(form.endDate)}}
				
				</div>
				
				<div class="col mt-5">
				
					<h4>Montant du séjour : <span id="amount">...</span> &euro; </h4>
					<span id="days">0</span> nuit(s) à {{ad.price}} &euro; /nuit
				
				</div>
		
			</div>
		
			<h5>Vous avez un commentaire ?</h5>
		
			{{form_row(form.comment)}}
		
			<button type="submit" class="btn btn-primary mt-3">Réserver</button>
		
			<a href="{{path('ads_single',{'slug':ad.slug})}}" class="btn btn-secondary mt-3">Retour</a>
		
		{{form_end(form)}}

	</div>

{% endblock %}

{% block javascripts %}
	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

	<script>
		
		$(document).ready(function() {
			
			$('#booking_startDate,#booking_endDate').datepicker(
			
				{format:'dd/mm/yyyy',
				startDate: new Date(),
				datesDisabled:[
				 	{% for day in ad.notAvailableDays %}
				
						"{{ day.format('d/m/Y') }}",
				
					{% endfor %}
				 ]
				
				}
			
			);
			
			$('#booking_startDate,#booking_endDate').on('change',calculateAmount);
			
		});
		
		function calculateAmount() {
			
			// Calculer l'intervale entre 2 dates
			
			const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));
			
			const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));
			
			// Comparer les 2 pour trouver le nombre de jours
			
			if(startDate && endDate && startDate < endDate) {
			
				const dayTime = 24*60*60*1000;

				const interval = endDate.getTime() - startDate.getTime();

				const days = interval / dayTime;
			
			// On multiplie l'intervale par le prix du bien
				
				const amount = days * {{ ad.price }};
			
			// Insertion des nombres dans la page
			
				$('#days').text(days);
			
				$('#amount').text(amount.toLocaleString('fr-FR'));
				
			}
			
		}
		
	</script>

{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n°{{booking.id}}{% endblock %}

{% block body %}

	<main class="container">

		<h1>
			Réservation n°{{booking.id}} du bien :
		</h1>
			<br>
		<h3>
			<a href="{{path('ads_single',{'slug':booking.ad.slug})}}">{{booking.ad.title}}</a>
		</h3>
		
		{% if app.request.query.get('alert') %}
		
			<div class="alert alert-success">
		
				<h4 class="alert-heading">Ok !</h4>
				
				<p>Votre réservation auprès de <a href="{{path('user_show',{'slug':booking.ad.author.slug})}}">{{booking.ad.author.fullName}}</a> pour l'annonce <a href="{{path('ads_single',{'slug':booking.ad.slug})}}">{{booking.ad.title}}</a> a bien été enregistrée.</p>
				
			</div>	
		
		{% endif %}
		
		<div class="row">
		
			<div class="col">
				
				<div class="alert alert-light mt-3">
				
					<h3>Détails</h3>
					<dl class="row">
						
						<dt class="col-md-4">Numéro :</dt>
						<dd class="col-md-8">{{booking.id}}</dd>
						
						<dt class="col-md-4">Date d'arrivée :</dt>
						<dd class="col-md-8">{{booking.startDate | date('d/m/Y')}}</dd>
						
						<dt class="col-md-4">Date de départ :</dt>
						<dd class="col-md-8">{{booking.endDate | date('d/m/Y')}}</dd>
						
						<dt class="col-md-4">Nombre de nuits :</dt>
						<dd class="col-md-8">{{booking.duration}}</dd>
						
						<dt class="col-md-4">Coût par nuit :</dt>
						<dd class="col-md-8">{{booking.ad.price}}</dd>
						
						<dt class="col-md-4">Montant total :</dt>
						<dd class="col-md-8">{{booking.amount}}</dd>
						
						<dt class="col-md-4">Commentaire :</dt>
						<dd class="col-md-8">{{booking.comment | default('Aucun commentaire')}}</dd>
					
					</dl>
					
					<h3 class="alert-heading">Propriétaire du bien</h3>
					
					<div class="row">
					
						<div class="col-md-3">
						
							<img src="{{booking.ad.author.avatar}}" alt="Avatar de {{booking.ad.author.fullName}}" class="avatar avatar-medium">
						
						</div>
					
						<div class="col-md-9">
							
							<h4 class="h5">
								<a href="{{path('user_show',{'slug':booking.ad.author.slug})}}">{{booking.ad.author.fullName}}</a>
							</h4>
							
							<span class="badge bg-primary">{{booking.ad.author.ads | length}} {% if booking.ad.author.ads | length > 1 %} annonces {% else %} annonce {% endif %}</span>
						
						</div>
						
						<div class="px-3 mt-3">
							{{booking.ad.author.description | raw}}
						
						</div>
						
					</div>
					
					<div class="alert alert-light" id="comment">
					
						<h3 class="alert-heading h5 mb-3">Votre avis nous intéresse !</h3>
						
						{% if date() > date(booking.endDate) %}
						
							{% set comment = booking.ad.commentFromAuthor(app.user) %}
						
							{% if comment is not null %}
						
								<blockquote>{{comment.content}}</blockquote>
						
								<strong>Note : </strong> {% include 'includes/rating.html.twig' with {'rating':comment.rating} %}
						
								{% else %}
								
									{{form_start(form)}}

									{{form_widget(form)}}

									<button type="submit" class="btn btn-primary mt-3">Envoyer</button>

									{{form_end(form)}}
						
							{% endif %}
						
						{% else %}
						
							<p class="alert alert-warning">Vous ne pouvez pas noter cette annonce tant que votre séjour n'est pas terminé.</p>
						
						{% endif %}
					
					</div>
				
				</div>
			
			</div>
			
			<div class="col">
			
				<div class="alert alert-light mt-3">
					
					<h3 class="alert-heading">Votre hébergement</h3>
					
					<h4><a href="{{path('ads_single',{'slug':booking.ad.slug})}}" class="btn btn-secondary">{{booking.ad.title}}</a></h4>
					
					<img src="{{booking.ad.coverImage}}" alt="Image de couverture de {{booking.ad.title}}" class="img-fluid">
					
					{{booking.ad.content | raw}}
					
					<a href="{{path('ads_single',{'slug':booking.ad.slug})}}" class="btn btn-secondary">Détails</a>
				
				</div>
			
			</div>
			
		</div>

	</main>

{% endblock %}