src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Repository\AdRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"title"},
 * message="Une autre annonce contient déjà ce titre, veuillez le modifier"
 * )
 */
class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
	 * @Assert\Length(min=10,max=255,minMessage="Le titre doit comporter + de 10 caractères",maxMessage="Le texte ne doit pas comporter + de 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
	 * @Assert\Length(min=30,minMessage="Veuillez rentrer au moins 30 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
	 * @Assert\Length(min=100,minMessage="Veuillez rentrer au moins 100 caractères")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad",orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }
	
	/**
	 * Création d'une fonction pour permettre d'initialiser le slug (avant la persistance et avant la màj)
	 * 
	 * @ORM\PrePersist
	 * @ORM\PreUpdate
	*/
	
	public function initializeSlug() {
                                             		
                   	if(empty($this->slug)) {
                                                 			
                   		$slugify = new Slugify();
                  			$this->slug = $slugify->slugify($this->title);
                                            			
                   	}                                          	
                   }
	
	/**
	 * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
	 * 
	 * @param User $author
	 * @return Comment|null
	*/
	
	public function getCommentFromAuthor(User $author) {
		
		foreach($this->comments as $comment) {
			
			if($comment->getAuthor() === $author) return $comment;
			
		}
		
		return null;
	}
	
	public function getAverageRatings() {
		
		// Calcul de la somme des notes
		
		$sum = array_reduce($this->comments->toArray(),function($total,$comment) {
			
			// On retourne le total + la note de chaque commentaire
			
			return $total + $comment->getRating();
			
		},0);
		
		// Diviser le total par le nombre de notes
		
		if (count($this->comments) > 0) return $sum / count($this->comments);
		
		return 0;
		
	}
	
	public function getNotAvailableDays() {
               		
               		$notAvailableDays = [];
               		
               		foreach($this->bookings as $booking) {
               			
               			// $resultat = range(10,20,2); => [10,12,14,16,18,20]
               			
               			$resultat = range(
               				$booking -> getStartDate()->getTimestamp(),
               				$booking -> getEndDate() -> getTimestamp(),
               				24 * 60 * 60
               				
               			);
               			
               			$days = array_map(function($dayTimestamp) {
               				
               				return new \DateTime(date('Y-m-d',$dayTimestamp));
               				
               			},$resultat);
               			
               			$notAvailableDays = array_merge($notAvailableDays,$days);
               				
               		}
               		
               		return $notAvailableDays;
               	}

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"email"},
 * message="Cette adresse mail est déjà utilisée")
 */

class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
	 * @Assert\NotBlank()
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
	 * @Assert\NotBlank()
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
	 * @Assert\Email(message="Veuillez renseigner un mail valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
	 * @Assert\Url()
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;
	/**
	 * Comparaison du champ ci-dessous avec le champ password
	 *
	 * @Assert\EqualTo(propertyPath="password",message="Les mots de passe ne correspondent pas")
	*/
	public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
	 * @Assert\Length(min=10,minMessage="Votre introduction doit comporter au moins 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
	 * @Assert\Length(min=100,minMessage="Votre description doit comporter au moins 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;
	
	public function getFullName() {
                                             		
    	return "{$this->firstname} {$this->lastname}";
                                             		
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }
	
	/**
	 * Création d'une fonction pour permettre d'initialiser le slug (avant la persistance et avant la màj)
	 * 
	 * @ORM\PrePersist
	 * @ORM\PreUpdate
	*/
	
	public function initializeSlug() {
                                                                              		
        if(empty($this->slug)) {
                                                                              			
            $slugify = new Slugify();
                                                    
            $this->slug = $slugify->slugify($this->firstname.' '.$this->lastname);
                                                                              			
        }
                                                                              		                          		
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }
	
	public function getRoles() {
                                             		
        $roles = $this->userRoles->map(function($role) {
                              						
        return $role->getTitle();
        })->toArray();
                              		
        $roles[]='ROLE_USER';
                              		
        return $roles;
                                             		
    }
	
	
	public function getSalt() {}
	
	public function getUsername() {
                                             		
        return $this->email;
                                             		
    }
	
	public function eraseCredentials() {}

    /**
     * @return Collection|Role[]
     */
	
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
	
}

templates/ad/_ad.html.twig
{% set url=path('ads_single',{'slug':ad.slug}) %}
			
			<div class="col-md-4">
			
				<div class="card">
				
					<div class="card-header bg-primary text-light">{{ad.rooms}} chambres <strong>{{ad.price}} &euro;/nuit</strong></div>
					
					<div class="card-body">
					
						<a href="{{url}}">
							<img src="{{ad.coverImage}}" alt="{{ad.title}}" style="height: 200px; width: 100%; display: block;">
						</a>
						
						<h4 class="card-title mt-3">{{ad.title}}</h4>
						
						<p class="card-text">{{ad.introduction}}</p>
						
						<a href="{{url}}" class="btn btn-dark">+ d'infos</a>
						
						{% if app.user and app.user == ad.author %}
							<a href="{{path('ads_edit',{'slug':ad.slug})}}" class="btn btn-dark">Modifier</a>
						{% endif %}
					
					</div>
					
					<div class="card-footer text-muted text-center">
						
						{% if ad.comments | length > 0 %}
					
						{% include 'includes/rating.html.twig' with {'rating':ad.averageRatings} %} sur {{ad.comments | length}} avis
						
						{% else %}
						
							<span>Pas encore noté</span>
						
						{% endif %}
					
					</div>
				
				</div>
			
			</div>
			

templates/ad/_collections.html.twig
{% block _annonce_images_widget %}

	<p>Ajouter des images supplémentaires</p>

	<input type="hidden" id="widget-count" value="0">

	<button type="button" class="btn btn-dark" id="add-image">Ajouter</button>

	{{ form_widget(form) }}

{% endblock %}

{% block _annonce_images_entry_row %}

	{{ form_widget(form) }}

{% endblock %}

{% block _annonce_images_entry_widget %}

	<div class="form-group" id="bloc_{{id}}">
		
		<div class="row">
			
			<div class="col-md-10 col-10">
			
				<div class="row">

					<div class="col">

						{{ form_widget(form.url) }}

					</div>

					<div class="col">

						{{ form_widget(form.caption) }}

					</div>

				</div>
			
			</div>
			
			<div class="col-md-2 col-2">
			
				<button type="button" class="btn btn-danger" data-action="delete" data-target="#bloc_{{id}}">X</button>
			
			</div>
			
		</div>

	</div>

{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %} Modifier une annonce {% endblock %}
{% form_theme form 'ad/_collections.html.twig' %}

{% block body %}

	<div class="container">

		<h1>Modification d'une annonce</h1>

		{{ form_start(form) }}
		
			{{ form_widget(form) }}
		
			<button type="submit" class="btn btn-primary">Enregistrer</button>

		{{ form_end(form) }}
		
	</div>

{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos annonces{% endblock %}

{% block body %}

	<main class="container">

		<h1 class="mt-5 mb-3">{{controller_name}}</h1>
		
		<div class="row">
		
			{% for ad in ads %}
			
				{% include 'ad/_ad.html.twig' %}
			
			{% endfor %}
		
		</div>
		
	</main>
		
{% endblock %}

templates/ad/new.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'ad/_collections.html.twig' %}

{% block body %}

	<div class="container">

		<h1>Création d'une nouvelle annonce</h1>

		{{ form_start(form) }}
		
			{{ form_widget(form) }}
		
			<button type="submit" class="btn btn-primary mt-2">Créer</button>

		{{ form_end(form) }}
		
	</div>

{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ad.title}}{% endblock %}

{% block body %}

	<div class="ad-title" style="background-image: url({{ad.coverImage}})">

		<div class="container">
			
			<h1 class="mt-3">{{ad.title}}</h1>
			<p>{{ad.introduction}}</p>
			<p class="h5">{{ad.rooms}} chambres pour <strong>>{{ad.price}} &euro; / nuit</strong></p>
			<a class="btn btn-secondary mt-3" href="{{path('booking_create',{'slug':ad.slug})}}">Réserver</a>
			
			{% if app.user and app.user == ad.author %}
				<a href="{{path('ads_edit',{'slug':ad.slug})}}" class="btn btn-secondary mt-3">Modifier l'annonce</a>
				<a href="{{path('ads_delete',{'slug':ad.slug})}}" class="btn btn-dark mt-3" onclick="return confirm(`Voulez-vous supprimer cette annonce ?`)">Supprimer l'annonce</a>
			{% endif %}
			
		</div>
	
	</div>

		<div class="container">

			<div class="row">
			
				<div class="col-md-8 mt-1 mb-3">
				
					{{ad.content|raw}}
					
					<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  
						<div class="carousel-indicators">
    							
							{% for image in ad.images %}
							
							<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{loop.index0}}" class="{% if loop.first %}active{% endif %}" aria-current="true" aria-label="Slide 1"></button>
							
							{% endfor %}
							
  						</div>
  
						<div class="carousel-inner">
							
							{% for image in ad.images %}
							
							<div class="carousel-item {% if loop.first %}active{% endif %}">
							  <img src="{{image.url}}" class="d-block w-100" alt="...">
							  	<div class="carousel-caption d-none d-md-block">
									<h5>{{ad.title}}
							  		</h5>
							  		<p>{{image.caption}}</p>
								</div>
							</div>
							
							{% endfor %}
  	
						</div>
										
  						<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    
							<span class="carousel-control-prev-icon" aria-hidden="true"></span>
    
							<span class="visually-hidden">Précédent</span>
  
						</button>
						
  						<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
							
    						<span class="carousel-control-next-icon" aria-hidden="true"></span>
    					
							<span class="visually-hidden">Suivant</span>
							
  						</button>
						
					</div>
					
					<hr>
					
					{% if ad.comments | length > 0 %}
					
						<h3>Commentaires des voyageurs</h3>
					
						<div class="alert alert-light">
						
							<h6 class="alert-heading">
								
								<div class="row align-items-center">
									
									<div class="col">
									
										Note globale des voyageurs :
									
									</div>
									
									<div class="col">
									
										{% include 'includes/rating.html.twig' with {'rating':ad.averageRatings} %}
										
										<br>
										
										<small class="text-lowercase">Cette moyenne est calculée sur {{ad.comments | length}} avis.</small>	
									
									</div>
								
								</div>
									
							</h6>
					
						</div>
					
						{% for comment in ad.comments %}
					
							<div class="bg-light-rounded">
					
								<p><strong>{{comment.author.fullName}}</strong> a dit : </p>
					
								<blockquote>{{comment.content}}</blockquote>
								
								<p>Note donnée : {% include 'includes/rating.html.twig' with {'rating' : comment.rating} %}</p>
								
							</div>
					
						{% endfor %}
					
					{% else %}
					
						<h5>Cette annonce n'a pas encore de commentaires.</h5>
					
					{% endif %}
				
				</div>
				
				<div class="col">
					
					{% set a = ad.author %}
				
					<div class="row">
					
						<div class="col-4">
						
							<a href="{{path('user_show',{'slug':a.slug})}}">
							
								<img src="{{a.avatar}}" alt="{{a.fullName}}" class="rounded-circle">
								
							</a>
						
						</div>
						
						<div class="col">
						
							<a href="{{path('user_show',{'slug':a.slug})}}">	
							
								<h3 class="ms-3">{{a.fullName}}</h3>
							
							</a>
							
							<span class="badge bg-light text-dark mb-4 ms-3">{{a.ads | length}} {% if a.ads | length > 1 %} annonces {% else %} annonce {% endif %}</span>
						
						</div>
					
					</div>
					
					<div class="col py-3">
					
						{{a.introduction | raw}}
					
					</div>
					
				</div>
			
			</div>

		</div>

{% endblock %}